import { bnOf, type Lang } from '@/lib/i18n'

const bnDigits = (s: string | number) => String(s).replace(/\d/g, (d) => '০১২৩৪৫৬৭৮৯'[Number(d)])


export const addFarmText = {
  en: {
    title: 'Add my farm',
    subtitle: 'Show FarmShield where your field is, anywhere in the world, and what you grow. NASA satellites will watch it for you.',
    steps: ['Where', 'Crop', 'Name'],
    whereTitle: 'Where is your field?',
    whereHint: 'Use your phone’s location, search for your village or town, or tap your field on the map.',
    search: 'Find your village or town',
    searchPlaceholder: 'e.g. Bogura, or Kiambu, Kenya',
    searchButton: 'Search',
    searching: 'Searching…',
    noResults: 'No places found. Try another spelling, or tap your field on the map.',
    searchDown: 'Search isn’t answering right now. Tap your field on the map instead.',
    useLocation: 'Use my location',
    locating: 'Finding you…',
    denied: 'Location permission was refused. Search for your place or tap the map instead.',
    unavailable: 'Your device couldn’t find its location. Search for your place or tap the map.',
    chooseDivision: 'In Bangladesh: choose your division and district',
    districtHint: 'Now tap your exact field on the map, or keep the district town.',
    mapLabel: 'World map. Tap your field to place the pin, or drag the pin.',
    tapMap: 'Tap your field on the map',
    viewMap: 'Map',
    viewSatellite: 'Satellite',
    near: (district: string, division: string) => `Near ${district}, ${division} division`,
    kmFrom: (km: number, district: string) => (km < 2 ? `In ${district} town` : `${km.toFixed(0)} km from ${district} town`),
    nearWorld: (place: string, country: string) => (country ? `Near ${place}, ${country}` : `Near ${place}`),
    unnamed: 'Your selected spot',
    water: 'This spot is open water. Tap on land to place your field.',
    worldNote: 'Outside Bangladesh, FarmShield fits its checks to your land’s shape and your soil, from NASA data.',
    checking: 'Checking the place…',
    cropTitle: 'What do you grow there?',
    cropHint: 'Each crop has its own heat limit and diseases, so the advice fits your field.',
    preview: 'Your field will look like this',
    nameTitle: 'Give your field a name',
    nameHint: 'So you can tell your fields apart. You can skip this.',
    nameLabel: 'Field name',
    defaultName: (crop: string) => `My ${crop.toLowerCase()} field`,
    summary: 'Your new farm',
    save: 'Save my farm',
    next: 'Next',
    back: 'Back',
    saved: (name: string) => `${name} added`,
    savedHint: 'Reading NASA data for your field. This takes a few seconds the first time.',
    privacy: 'Your farms are saved only on this device.',
    loadError: 'Couldn’t load the list of places and crops. Check your connection and try again.',
    retry: 'Try again',
  },
  bn: {
    title: 'আমার জমি যোগ করুন',
    subtitle: 'আপনার জমি কোথায় (পৃথিবীর যেকোনো জায়গায়) আর কী চাষ করছেন তা জানান। নাসার উপগ্রহ আপনার জমির খেয়াল রাখবে।',
    steps: ['কোথায়', 'ফসল', 'নাম'],
    whereTitle: 'আপনার জমি কোথায়?',
    whereHint: 'ফোনের লোকেশন ব্যবহার করুন, আপনার গ্রাম বা শহর খুঁজুন, অথবা মানচিত্রে আপনার জমিতে চাপ দিন।',
    search: 'আপনার গ্রাম বা শহর খুঁজুন',
    searchPlaceholder: 'যেমন: বগুড়া, বা Kiambu, Kenya',
    searchButton: 'খুঁজুন',
    searching: 'খুঁজছি…',
    noResults: 'কোনো জায়গা পাওয়া যায়নি। অন্য বানানে চেষ্টা করুন, বা মানচিত্রে জমিতে চাপ দিন।',
    searchDown: 'এখন খোঁজা যাচ্ছে না। মানচিত্রে আপনার জমিতে চাপ দিন।',
    useLocation: 'আমার লোকেশন ব্যবহার করুন',
    locating: 'খুঁজছি…',
    denied: 'লোকেশনের অনুমতি দেওয়া হয়নি। জায়গা খুঁজুন বা মানচিত্রে চাপ দিন।',
    unavailable: 'আপনার ডিভাইস লোকেশন খুঁজে পায়নি। জায়গা খুঁজুন বা মানচিত্রে চাপ দিন।',
    chooseDivision: 'বাংলাদেশে: বিভাগ ও জেলা বেছে নিন',
    districtHint: 'এখন মানচিত্রে আপনার জমির সঠিক জায়গায় চাপ দিন, অথবা জেলা শহরই রাখুন।',
    mapLabel: 'বিশ্বের মানচিত্র। পিন বসাতে আপনার জমিতে চাপ দিন, অথবা পিন টেনে সরান।',
    tapMap: 'মানচিত্রে আপনার জমিতে চাপ দিন',
    viewMap: 'মানচিত্র',
    viewSatellite: 'উপগ্রহ',
    near: (district: string, division: string) => `${bnOf(district)} কাছে, ${division} বিভাগ`,
    kmFrom: (km: number, district: string) => (km < 2 ? `${district} শহরে` : `${district} শহর থেকে ${bnDigits(km.toFixed(0))} কিমি`),
    nearWorld: (place: string, country: string) => (country ? `${bnOf(place)} কাছে, ${country}` : `${bnOf(place)} কাছে`),
    unnamed: 'আপনার বেছে নেওয়া জায়গা',
    water: 'এই জায়গাটি খোলা পানি। জমি বসাতে স্থলভাগে চাপ দিন।',
    worldNote: 'বাংলাদেশের বাইরে ফার্মশিল্ড নাসার তথ্য দিয়ে আপনার জমির ঢাল আর মাটির ধরন অনুযায়ী হিসাব মিলিয়ে নেয়।',
    checking: 'জায়গাটি দেখছি…',
    cropTitle: 'সেখানে কী চাষ করছেন?',
    cropHint: 'প্রতিটি ফসলের সহ্যের তাপমাত্রা আর রোগ আলাদা, তাই পরামর্শ আপনার জমির মতো হবে।',
    preview: 'আপনার জমি দেখতে এমন হবে',
    nameTitle: 'জমির একটি নাম দিন',
    nameHint: 'যাতে আপনার জমিগুলো আলাদা করে চিনতে পারেন। চাইলে বাদ দিতে পারেন।',
    nameLabel: 'জমির নাম',
    defaultName: (crop: string) => `আমার ${bnOf(crop)} জমি`,
    summary: 'আপনার নতুন জমি',
    save: 'জমি সংরক্ষণ করুন',
    next: 'পরের ধাপ',
    back: 'পেছনে',
    saved: (name: string) => `${name} যোগ হয়েছে`,
    savedHint: 'আপনার জমির নাসা তথ্য পড়ছি। প্রথমবার কয়েক সেকেন্ড লাগে।',
    privacy: 'আপনার জমির তথ্য শুধু এই ডিভাইসে রাখা হয়।',
    loadError: 'জায়গা ও ফসলের তালিকা আনা যায়নি। সংযোগ দেখে আবার চেষ্টা করুন।',
    retry: 'আবার চেষ্টা করুন',
  },
} satisfies Record<Lang, Record<string, unknown>>
