import { bnOf, type Lang } from '@/lib/i18n'

const bnDigits = (s: string | number) => String(s).replace(/\d/g, (d) => '০১২৩৪৫৬৭৮৯'[Number(d)])


export const addFarmText = {
  en: {
    title: 'Add my farm',
    subtitle: 'Show FarmShield where your field is and what you grow. NASA satellites will watch it for you.',
    steps: ['Where', 'Crop', 'Name'],
    whereTitle: 'Where is your field?',
    whereHint: 'Use your phone’s location, choose your district, or tap your field on the map.',
    useLocation: 'Use my location',
    locating: 'Finding you…',
    denied: 'Location permission was refused. Choose your district or tap the map instead.',
    unavailable: 'Your device couldn’t find its location. Choose your district or tap the map.',
    gpsOutside: 'Your location seems to be outside Bangladesh. Choose your district or tap the map.',
    chooseDivision: 'Or choose your division and district',
    districtHint: 'Now tap your exact field on the map, or keep the district town.',
    mapLabel: 'Map of Bangladesh. Tap your field to place the pin, or drag the pin.',
    tapMap: 'Tap your field on the map',
    viewMap: 'Map',
    viewSatellite: 'Satellite',
    near: (district: string, division: string) => `Near ${district}, ${division} division`,
    kmFrom: (km: number, district: string) => (km < 2 ? `In ${district} town` : `${km.toFixed(0)} km from ${district} town`),
    outside: 'This spot is outside Bangladesh. FarmShield covers Bangladeshi farmland for now.',
    checking: 'Checking the place…',
    cropTitle: 'What do you grow there?',
    cropHint: 'Each crop has its own heat limit and diseases, so the advice fits your field.',
    preview: 'Your field will look like this',
    nameTitle: 'Give your field a name',
    nameHint: 'So you can tell your fields apart. You can skip this.',
    nameLabel: 'Field name',
    defaultName: (crop: string) => `My ${crop.toLowerCase()} field`,
    summary: 'Your new farm',
    save: 'Save my farm',
    next: 'Next',
    back: 'Back',
    saved: (name: string) => `${name} added`,
    savedHint: 'Reading NASA data for your field. This takes a few seconds the first time.',
    privacy: 'Your farms are saved only on this device.',
    loadError: 'Couldn’t load the list of places and crops. Check your connection and try again.',
    retry: 'Try again',
  },
  bn: {
    title: 'আমার জমি যোগ করুন',
    subtitle: 'আপনার জমি কোথায় আর কী চাষ করছেন তা জানান। নাসার উপগ্রহ আপনার জমির খেয়াল রাখবে।',
    steps: ['কোথায়', 'ফসল', 'নাম'],
    whereTitle: 'আপনার জমি কোথায়?',
    whereHint: 'ফোনের লোকেশন ব্যবহার করুন, জেলা বেছে নিন, অথবা মানচিত্রে আপনার জমিতে চাপ দিন।',
    useLocation: 'আমার লোকেশন ব্যবহার করুন',
    locating: 'খুঁজছি…',
    denied: 'লোকেশনের অনুমতি দেওয়া হয়নি। জেলা বেছে নিন বা মানচিত্রে চাপ দিন।',
    unavailable: 'আপনার ডিভাইস লোকেশন খুঁজে পায়নি। জেলা বেছে নিন বা মানচিত্রে চাপ দিন।',
    gpsOutside: 'আপনার লোকেশন বাংলাদেশের বাইরে মনে হচ্ছে। জেলা বেছে নিন বা মানচিত্রে চাপ দিন।',
    chooseDivision: 'অথবা বিভাগ ও জেলা বেছে নিন',
    districtHint: 'এখন মানচিত্রে আপনার জমির সঠিক জায়গায় চাপ দিন, অথবা জেলা শহরই রাখুন।',
    mapLabel: 'বাংলাদেশের মানচিত্র। পিন বসাতে আপনার জমিতে চাপ দিন, অথবা পিন টেনে সরান।',
    tapMap: 'মানচিত্রে আপনার জমিতে চাপ দিন',
    viewMap: 'মানচিত্র',
    viewSatellite: 'উপগ্রহ',
    near: (district: string, division: string) => `${bnOf(district)} কাছে, ${division} বিভাগ`,
    kmFrom: (km: number, district: string) => (km < 2 ? `${district} শহরে` : `${district} শহর থেকে ${bnDigits(km.toFixed(0))} কিমি`),
    outside: 'এই জায়গাটি বাংলাদেশের বাইরে। ফার্মশিল্ড এখন শুধু বাংলাদেশের জমির জন্য।',
    checking: 'জায়গাটি দেখছি…',
    cropTitle: 'সেখানে কী চাষ করছেন?',
    cropHint: 'প্রতিটি ফসলের সহ্যের তাপমাত্রা আর রোগ আলাদা, তাই পরামর্শ আপনার জমির মতো হবে।',
    preview: 'আপনার জমি দেখতে এমন হবে',
    nameTitle: 'জমির একটি নাম দিন',
    nameHint: 'যাতে আপনার জমিগুলো আলাদা করে চিনতে পারেন। চাইলে বাদ দিতে পারেন।',
    nameLabel: 'জমির নাম',
    defaultName: (crop: string) => `আমার ${bnOf(crop)} জমি`,
    summary: 'আপনার নতুন জমি',
    save: 'জমি সংরক্ষণ করুন',
    next: 'পরের ধাপ',
    back: 'পেছনে',
    saved: (name: string) => `${name} যোগ হয়েছে`,
    savedHint: 'আপনার জমির নাসা তথ্য পড়ছি। প্রথমবার কয়েক সেকেন্ড লাগে।',
    privacy: 'আপনার জমির তথ্য শুধু এই ডিভাইসে রাখা হয়।',
    loadError: 'জায়গা ও ফসলের তালিকা আনা যায়নি। সংযোগ দেখে আবার চেষ্টা করুন।',
    retry: 'আবার চেষ্টা করুন',
  },
} satisfies Record<Lang, Record<string, unknown>>
